apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-data
spec:
  storageClassName: elastic-data
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/elastic/
