---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      external_labels:
        monitor: 'eks-dev-monitor'
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: "pod_dev"
        static_configs:
           - targets: ['pushgateway.dev.svc.cluster.local:9091']
      - job_name: "pod_test"
        static_configs:
           - targets: ['pushgateway.test.svc.cluster.local:9091']
      - job_name: "pod_prod"
        static_configs:
           - targets: ['pushgateway.prod.svc.cluster.local:9091']
